In [ ]:
# working with date and time 
#

In [7]:
import numpy as np
import pandas as pd
date = pd.read_csv('orders.csv', parse_dates=["date"])
time = pd.read_csv('messages.csv', parse_dates=["date"])
date.head()
time.head()

                 date                                                msg
0 2013-12-15 00:50:00                           ищу на сегодня мужика 37
1 2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2 2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3 2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4 2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [9]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
365 2018-07-18        6248        4       2       2018
47  2018-12-11        3437       14       2       2018
118 2019-03-12        2251        9       1       2019
885 2019-07-03        7368       25       1       2019
381 2019-04-12        2837       18     149       2019

In [10]:
date['date_month_no'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [11]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

In [12]:
date['date_day'] = date['date'].dt.day

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [ ]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year  date_month_no date_month_name  date_day date_dow_name
0 2019-12-10       2019             12        December        10       Tuesday
1 2018-08-15       2018              8          August        15     Wednesday
2 2018-10-23       2018             10         October        23       Tuesday
3 2019-08-17       2019              8          August        17      Saturday
4 2019-01-06       2019              1         January         6        Sunday

In [14]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,Tuesday,0
1,2018-08-15,2018,8,August,15,Wednesday,0
2,2018-10-23,2018,10,October,23,Tuesday,0
3,2019-08-17,2019,8,August,17,Saturday,1
4,2019-01-06,2019,1,January,6,Sunday,1

In [15]:
date['date_week'] = date['date'].dt.week

date.drop(columns=['product_id','city_id','orders']).head()

AttributeError: 'DatetimeProperties' object has no attribute 'week'

In [16]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow_name,date_is_weekend,quarter
0,2019-12-10,2019,12,December,10,Tuesday,0,4
1,2018-08-15,2018,8,August,15,Wednesday,0,3
2,2018-10-23,2018,10,October,23,Tuesday,0,4
3,2019-08-17,2019,8,August,17,Saturday,1,3
4,2019-01-06,2019,1,January,6,Sunday,1,1

In [17]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow_name,date_is_weekend,quarter,semester
0,2019-12-10,2019,12,December,10,Tuesday,0,4,2
1,2018-08-15,2018,8,August,15,Wednesday,0,3,2
2,2018-10-23,2018,10,October,23,Tuesday,0,4,2
3,2019-08-17,2019,8,August,17,Saturday,1,3,2
4,2019-01-06,2019,1,January,6,Sunday,1,1,1

In [18]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2025, 2, 26, 13, 38, 41, 635317)

In [19]:
today - date['date']

0     1905 days 13:38:41.635317
1     2387 days 13:38:41.635317
2     2318 days 13:38:41.635317
3     2020 days 13:38:41.635317
4     2243 days 13:38:41.635317
                 ...
995   2333 days 13:38:41.635317
996   2274 days 13:38:41.635317
997   2122 days 13:38:41.635317
998   2187 days 13:38:41.635317
999   1961 days 13:38:41.635317
Name: date, Length: 1000, dtype: timedelta64[ns]

In [21]:
# Months passed

np.round((today -date['date']) / np.timedelta64(1, 'm'),0)

0      2744019.0
1      3438099.0
2      3338739.0
3      2909619.0
4      3230739.0
         ...
995    3360339.0
996    3275379.0
997    3056499.0
998    3150099.0
999    2824659.0
Name: date, Length: 1000, dtype: float64

In [22]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [23]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [24]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23:11:00

In [25]:
today - time['date']

0     4091 days 12:48:41.635317
1     3955 days 13:58:41.635317
2     4441 days 13:17:41.635317
3     3743 days 13:07:41.635317
4     4140 days 14:27:41.635317
                 ...
995   4730 days 12:48:41.635317
996   4051 days 14:24:41.635317
997   4516 days 14:01:41.635317
998   4632 days 14:04:41.635317
999   3904 days 14:13:41.635317
Name: date, Length: 1000, dtype: timedelta64[ns]